### PR TITLE
update browserify (fixes #9)

### LINKED ISSUE #9: PNG files with alpha channel in firefox, IE and Edge cause error
[The error also exist in bpampuch/pdfmake](https://github.com/bpampuch/pdfmake/issues/660).
@eeedvisss described the behavior as following:

> When passing transparent PNG image as Data-URL to image property, we get 'RangeError: invalid array length' on Firefox v48(worked perfectly on v47) and 'Invalid offset/length when creating typed array' on Microsoft Edge. This crashes all of PDF generator completely.
You can easily reproduce this on pdfmake playground 'IMAGES' tab, by passing PNG Data-URL with transparency.
Also if we pass PNG without transparency we just see empty space where image should be visible.

@FastestRobot described a temporary fix in his answer on [issue 577](https://github.com/bpampuch/pdfmake/issues/577#issuecomment-241249420)

I am currently not sure how to make according changes to get this upstream.
I am not even sure if this is a pdfmake related issue, a pdfkit related issue or a rather node.js related issue.

### PR DESCRIPTION
**Pull request by tsiegleauq**
Updates browserify to version 5.0.0
This fixes Invalid offset/length error in Firefox and IE and the handling of transparent PNG files

Compare:
[Invalid offset/length when creating typed array - pdfmake.js (24651,9) on Edge Windows 10](https://github.com/bpampuch/pdfmake/issues/577)
[Transparent PNG images on Edge and Firefox v48 return 'RangeError: invalid array length', crashes PDF generator](https://github.com/bpampuch/pdfmake/issues/660)
[pdfMake Firefox has problems with (large) .png files](https://github.com/OpenSlides/OpenSlides/issues/2287)

### CODE REVIEW

**Comment by miltador** [comment]
@tsiegleauq , thanks for digging into this problem and this PR!

**Comment by angularnewbee** [comment]
how can we get this fix? is it released?

**Comment by tsiegleauq** [comment]
> how can we get this fix? is it released?

there alreasy is [an issue](https://github.com/pdfmake/pdfmake/issues/16) for that.

**Comment by sorb999** [comment]
I am going through same issue. can any one tell me the solution for this?

**Pull request merged**
